# providers
providers = ["python"]

# python
[phases.setup]
nixpkgs = ["python310", "gcc"]
cmds = ["pip install --upgrade pip"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[start]
cmd = "cd backend && python -m uvicorn api.main:app --host 0.0.0.0 --port ${PORT:-8000}"
